CAID/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path("", include("Personal_Data.urls")),
    path("", include("Company_Data.urls")),
    path("", include("Reporting_Data.urls")),
    path('admin/', admin.site.urls)
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personal_Data/urls.py
from turtle import home
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("", views.home, name="home"),
        # Replace the existing path for ""
    path("hello/<name>", views.hello_there, name="hello_there"),
    path("about/", views.about, name="about"),
    path("personal_data/", views.personal_data, name="personal_data"),
    path("personal_data_name/", views.personal_data_name, name="personal_data_name"),
    path("personal_data/<str:code__no>/", views.personal_data_no, name="personal_data"),
    path('personal_data_edit/<str:id>/', views.personal_data_edit, name='personal_data_edit'),
    path('personal_data_edit/', views.personal_data, name='personal_data_edit'),
    path("personal_data_add/", views.personal_data_entry, name="personal_data_add"),
    # path("contact/", views.contact, name="contact"),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Personal_Data/models.py
from django.db import models

# Create your models here.


class personal_file(models.Model):
    code_no =  models.CharField(max_length= 4, primary_key=True)
    name = models.CharField(max_length=50)
    passport_size_photo = models.FileField(upload_to='personal_file', blank=True, null=True)
    pan_card = models.FileField(upload_to='personal_file', blank=True, null=True)
    pan_no = models.CharField(max_length=50)
    aadhar_card = models.FileField(upload_to='personal_file', blank=True, null=True)
    aadhar_card_no = models.CharField(max_length=50)
    passport = models.FileField(upload_to='personal_file', blank=True, null=True)
    passport_no = models.CharField(max_length=50)
    driving_licence = models.FileField(upload_to='personal_file', blank=True, null=True)
    driving_licence_no = models.CharField(max_length=50)
    gst = models.FileField(upload_to='personal_file', blank=True, null=True)
    gst_no = models.CharField(max_length=50)
    din = models.FileField(upload_to='personal_file', blank=True, null=True)
    din_no = models.CharField(max_length=50, unique= True)
    PTEC = models.FileField(upload_to='personal_file', blank=True, null=True)
    PTEC_no = models.CharField(max_length=50)
    
    # Passport_Photo = models.FileField(upload_to='personal_file', blank=True, null=True)
    # Passport_Photo = models.FileField(upload_to='personal_file', blank=True, null=True)
    Remarks = models.CharField(max_length=300)
    
    def __str__(self):
         return (self.code_no)
    

Personal_Data/forms.py
from django import forms
from .models import *

# class DateInput(forms.DateInput):
#     input_type = 'date'


class Add_Personal_Data(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = personal_file
        fields = "__all__"

class Search_Personal_Data(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = personal_file
        fields = ['code_no']


# class Product(forms.ModelForm):
#     # specify the name of model to use
#     class Meta:
#         model = Add_Product
#         fields = ['Product_Name']


# class Sale_Form(forms.ModelForm):
#     # specify the name of model to use
#     class Meta:
#         model = Customer_Sale
#         fields = "__all__"
#         widgets = {
#             'Sale_Date': DateInput(),
#             'Payment_Date': DateInput()
#         }

Personal_Data/templates/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from datetime import datetime
from .models import *
from PIL import Image
from django.conf import settings
from .forms import *
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.

# DIN KYC VIEWS

def DIN_KYC_entry(request):
    title = "DIN KYC Entry"
    form = Add_DIN_KYC()
    if request.method == 'POST':
        form = Add_DIN_KYC(request.POST, request.FILES)
        if form.is_valid():
            # save the form data to model
            photo = form.save(commit=False)
            # set the uploader to the user before saving the model
            photo.uploader = request.user
            # now we can save
            photo.save()
            return redirect("DIN_KYC") 
    return render(request, "input_data.html" , {'data': form , 'title':title})


def DIN_KYC(request):
    title = "DIN KYC"
    if request.method == 'POST':
            code = request.POST.get('DIN_no')
            if(DIN_KYC_file.objects.filter(din_no=code).exists()):
                data = DIN_KYC_file.objects.filter(din_no=code)
                a = True
                return render(request,'DIN_KYC_search.html' ,{'title' : title , 'data' : data , 'a' : a })     
            else:
                errors = 'Invalid code'
                a = False
                return render(request,'DIN_KYC_search.html' ,{'title' : title , 'errors': errors , 'a' : a})     
    return render( request, "DIN_KYC_search.html", { 'title' : title})


def DIN_KYC_edit(request, id):
    band = DIN_KYC_file.objects.get(din_no=id)

    if request.method == 'POST':
        #https://openclassrooms.com/en/courses/6967196-create-a-web-application-with-django/7349667-update-a-model-object-with-a-modelform
        #https://stackoverflow.com/questions/63298721/how-to-update-imagefield-in-django
        form = Add_DIN_KYC(request.POST, request.FILES, instance=band)
        if form.is_valid():
            # update the existing `Band` in the database
            # photo = form.save(commit=False)
            # # set the uploader to the user before saving the model
            # photo.uploader = request.user
            # now we can save
            form.save()            
            # redirect to the detail page of the `Band` we just updated
            return redirect('DIN_KYC', band.din_no)
    else:
        form = Add_DIN_KYC(instance=band)

    return render(request,
                'update_data.html',
                {'form': form})
    
def DIN_KYC_no(request, code__no):
    title = "DIN KYC"
    if(DIN_KYC_file.objects.filter(din_no=code__no).exists()):
        data = DIN_KYC_file.objects.filter(din_no=code__no)
        a = True
        return render(request,'DIN_KYC_search.html' ,{'title' : title , 'data' : data , 'a' : a })     
    else:
        errors = 'Invalid code'
        a = False
        return render(request,'DIN_KYC_search.html' ,{'title' : title , 'errors': errors , 'a' : a})     

# def DIN_KYC_list(request):
#     title = "DIN KYC LIST"
#     data = DIN_KYC_file.objects.values()
#     return render(request,'list.html' ,{'title' : title , 'data' : data})     



# PTEC VIEWS


def PTEC_entry(request):
    title = "PTEC Entry"
    form = Add_PTEC_no()
    if request.method == 'POST':
        form = Add_PTEC_no(request.POST, request.FILES)
        if form.is_valid():
            # save the form data to model
            photo = form.save(commit=False)
            # set the uploader to the user before saving the model
            photo.uploader = request.user
            # now we can save
            photo.save()
            return redirect("PTEC") 
    return render(request, "input_data.html" , {'data': form , 'title':title})


def PTEC(request):
    title = "PTEC"
    if request.method == 'POST':
            code = request.POST.get('DIN_no')
            if(PTEC_no_file.objects.filter(PTEC_no=code).exists()):
                data = PTEC_no_file.objects.filter(PTEC_no=code)
                a = True
                return render(request,'PTEC_search.html' ,{'title' : title , 'data' : data , 'a' : a })     
            else:
                errors = 'Invalid code'
                a = False
                return render(request,'PTEC_search.html' ,{'title' : title , 'errors': errors , 'a' : a})     
    return render( request, "PTEC_search.html", { 'title' : title})


def PTEC_edit(request, id):
    band = PTEC_no_file.objects.get(PTEC_no=id)

    if request.method == 'POST':
        #https://openclassrooms.com/en/courses/6967196-create-a-web-application-with-django/7349667-update-a-model-object-with-a-modelform
        #https://stackoverflow.com/questions/63298721/how-to-update-imagefield-in-django
        form = Add_PTEC_no(request.POST, request.FILES, instance=band)
        if form.is_valid():
            # update the existing `Band` in the database
            # photo = form.save(commit=False)
            # # set the uploader to the user before saving the model
            # photo.uploader = request.user
            # now we can save
            form.save()            
            # redirect to the detail page of the `Band` we just updated
            return redirect('PTEC', band.PTEC_no)
    else:
        form = Add_PTEC_no(instance=band)

    return render(request,
                'update_data.html',
                {'form': form})
    
def PTEC_no(request, code__no):
    title = "PTEC"
    if(PTEC_no_file.objects.filter(PTEC_no=code__no).exists()):
        data = PTEC_no_file.objects.filter(PTEC_no=code__no)
        a = True
        return render(request,'PTEC_search.html' ,{'title' : title , 'data' : data , 'a' : a })     
    else:
        errors = 'Invalid code'
        a = False
        return render(request,'PTEC_search.html' ,{'title' : title , 'errors': errors , 'a' : a})     


# PTRC VIEWS


def PTRC_entry(request):
    title = "PTRC Entry"
    form = Add_PTRC_no_data()
    if request.method == 'POST':
        form = Add_PTRC_no_data(request.POST, request.FILES)
        if form.is_valid():
            # save the form data to model
            photo = form.save(commit=False)
            # set the uploader to the user before saving the model
            photo.uploader = request.user
            # now we can save
            photo.save()
            return redirect("PTRC") 
    return render(request, "input_data.html" , {'data': form , 'title':title})

def PTRC_no_entry(request):
    title = "PTRC No Entry"
    form = Add_PTRC_no()
    if request.method == 'POST':
        form = Add_PTRC_no(request.POST, request.FILES)
        if form.is_valid():
            # save the form data to model
            photo = form.save(commit=False)
            # set the uploader to the user before saving the model
            photo.uploader = request.user
            # now we can save
            photo.save()
            return redirect("PTRC") 
    return render(request, "input_data.html" , {'data': form , 'title':title})


def PTRC(request):
    title = "PTRC"
    if request.method == 'POST':
            code = request.POST.get('DIN_no')
            if(PTRC_no_file.objects.filter(PTRC_no=code).exists()):
                data = PTRC_no_file.objects.filter(PTRC_no=code)
                a = True
                return render(request,'PTRC_search.html' ,{'title' : title , 'data' : data , 'a' : a })     
            else:
                errors = 'Invalid code'
                a = False
                return render(request,'PTRC_search.html' ,{'title' : title , 'errors': errors , 'a' : a})     
    return render( request, "PTRC_search.html", { 'title' : title})


def PTRC_edit(request, id):
    band = PTRC_no_file.objects.get(PTRC_no=id)

    if request.method == 'POST':
        #https://openclassrooms.com/en/courses/6967196-create-a-web-application-with-django/7349667-update-a-model-object-with-a-modelform
        #https://stackoverflow.com/questions/63298721/how-to-update-imagefield-in-django
        form = Add_PTRC_no_data(request.POST, request.FILES, instance=band)
        if form.is_valid():
            # update the existing `Band` in the database
            # photo = form.save(commit=False)
            # # set the uploader to the user before saving the model
            # photo.uploader = request.user
            # now we can save
            form.save()            
            # redirect to the detail page of the `Band` we just updated
            return redirect('PTRC', band.PTRC_no)
    else:
        form = Add_PTRC_no_data(instance=band)

    return render(request,
                'update_data.html',
                {'form': form})
    
def PTRC_no(request, code__no):
    title = "PTRC"
    if(PTRC_no_file.objects.filter(PTRC_no=code__no).exists()):
        data = PTRC_no_file.objects.filter(PTRC_no=code__no)
        a = True
        return render(request,'PTRC_search.html' ,{'title' : title , 'data' : data , 'a' : a })     
    else:
        errors = 'Invalid code'
        a = False
        return render(request,'PTRC_search.html' ,{'title' : title , 'errors': errors , 'a' : a})     

Personal_Data/templates/DIN_KYC_search.html
{% extends "layout.html" %}
{% block title %}
{{title}}{% endblock %}
{% block heading %}
{{title}}{% endblock %}
{% block content %}
{% load static %}






<style>
    .btnsubmit {
        width: 80px;
        height: 35px;
    }
</style>

                        
                <div class="row mt-2">
                    <div class="col-lg-10">
                        <form method="post" style="margin-top: 5%" action="{% url 'DIN_KYC' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6 col-12 mb-3 text-center">
                                    <label for="DIN no">DIN no</label>
                                </div>
                                <div class="col-lg-6 col-12 mb-3 text-center">
                                    <input type="text" name="DIN_no" maxlength="24" required id="id_DIN_no">
                                </div>
                                <div class="col-12 text-center">
                                    <input type="submit" class="btn btn-primary btnsubmit" value="Submit">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
               
                {% if a == True %}
                <div class="container col-lg-8 mt-5">
                    <table class="table">

                        <tbody>
                            {% for each in data %}
                            <tr>
                              <td>Din no</td>
                              <td>{{each.din_no}}</td>
                            </tr>
                            <tr>
                              <td>KYC date</td>
                              <td>{{each.KYC_date}}</td>
                            </tr>
                            <tr>
                              <td>KYC year</td>
                              <td>{{each.KYC_year}}</td>
                            </tr>
                              <tr>
                                <td>KYC proof</td>
                                <td>
                                  {% if each.KYC_proof %}
                                  <a href="/media/{{each.KYC_proof}}">KYC_proof</a>
                                  {% else %}
                                  KYC_proof not uploaded
                                  {% endif %}
                               </td>
                              </tr>
                              
                              <tr>
                                <td>Remarks</td>
                                    <td>
                                        {{each.Remarks}}
                                    </td>
                              </tr>
                              <tr> <td style="text-align: center ">
                                <a href=" {% url 'DIN_KYC_edit' %}{{ each.din_no }}" class="btn btn-primary btnsubmit">Edit</a>
                              </td> </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    <hr>
                {% endif %}
            </div>
        </div>
    </div>

    {% if a == False %}
    <div id="InfoBanner">
        <span class="reversed reversedRight">
          <span>
            &#9888;
          </span>
        </span>
        <span class="reversed reversedLeft">
          Warning {{errors}}!!
        </span>
    </div>
    {% endif %}



{% endblock %}

Personal_Data/templates/about.html
{% extends "layout.html" %}
{% block title %}
About us
{% endblock %}
{% block heading %}
About us
{% endblock %}
{% block content %}
<p>About page for the Software Devloper and Owner.</p>
{% endblock %}

Personal_Data/templates/company_data_search.html
{% extends "layout.html" %}
{% block title %}
{{title}}{% endblock %}
{% block heading %}
{{title}}{% endblock %}
{% block content %}
{% load static %}






<style>
    .btnsubmit {
        width: 80px;
        height: 35px;
    }
</style>

                        
                <div class="row mt-2">
                    <div class="col-lg-10">
                        <form method="post" style="margin-top: 5%" action="{% url 'company_data' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6 col-12 mb-3 text-center">
                                    <label for="Code no">Code no</label>
                                </div>
                                <div class="col-lg-6 col-12 mb-3 text-center">
                                    <input type="text" name="code_no" maxlength="4" required id="id_code_no">
                                </div>
                                <div class="col-12 text-center">
                                    <input type="submit" class="btn btn-primary btnsubmit" value="Submit">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row mt-2">
                  <div class="col-lg-10">
                      <form method="post" style="margin-top: 5%" action="{% url 'company_data_name' %}">
                          {% csrf_token %}
                          <div class="row">
                              <div class="col-lg-6 col-12 mb-3 text-center">
                                  <label for="name">Name</label>
                              </div>
                              <div class="col-lg-6 col-12 mb-3 text-center">
                                  <input type="text" name="name" maxlength="15" required id="id_name">
                              </div>
                              <div class="col-12 text-center">
                                  <input type="submit" class="btn btn-primary btnsubmit" value="Submit">
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
                {% if a == True %}
                <div class="container col-lg-8 mt-5">
                    <table class="table">

                        <tbody>
                            {% for each in data %}
                            <tr>
                                <td>Code no</td>
                                <td>{{each.code_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Name</td>
                                <td>{{each.name}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Pan card</td>
                                <td>
                                  {% if each.pan_card %}
                                  <a href="/media/{{each.pan_card}}">Pan Card</a>
                                  {% else %}
                                  Pan Card not uploaded
                                  {% endif %}
                               </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Pan no</td>
                                <td>{{each.pan_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Udyam aadhar</td>
                                <td>
                                  {% if each.udyam_aadhar %}
                                  <a href="/media/{{each.udyam_aadhar}}">Udyam aadhar</a>
                                  {% else %}
                                  Udyam aadhar not uploaded
                                  {% endif %}
                               </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Udyam aadhar no</td>
                                <td>{{each.udyam_aadhar_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Tan</td>
                                <td>
                                  {% if each.tan %}
                                  <a href="/media/{{each.tan}}">Tan</a>
                                  {% else %}
                                  Tan not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Tan no</td>
                                <td>{{each.tan_no}}</td>
                              </tr>
                              <tr>
                              <tr>
                                <td>Gst</td>
                                <td>
                                  {% if each.gst %}
                                  <a href="/media/{{each.gst}}">Gst</a>
                                  {% else %}
                                  Gst not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Gst no</td>
                                <td>{{each.gst_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Din</td>
                                <td>
                                  {% if each.din %}
                                  <a href="/media/{{each.din}}">DIN</a>
                                  {% else %}
                                  DIN not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Din no</td>
                                <td>{{each.din_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>PTEC</td>
                                <td>
                                  {% if each.PTEC %}
                                  <a href="/media/{{each.PTEC}}">PTEC</a>
                                  {% else %}
                                  PTEC not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>PTEC no</td>
                                <td>{{each.PTEC_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>PTRC</td>
                                <td>
                                  {% if each.PTRC %}
                                  <a href="/media/{{each.PTRC}}">PTRC</a>
                                  {% else %}
                                  PTRC not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>PTRC no</td>
                                <td>{{each.PTRC_no}}</td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Incorporation certificate</td>
                                <td>
                                  {% if each.incorporation_certificate %}
                                  <a href="/media/{{each.incorporation_certificate}}">Incorporation certificate</a>
                                  {% else %}
                                  Incorporation certificate not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Partnership deed</td>
                                <td>
                                  {% if each.partnership_deed %}
                                  <a href="/media/{{each.partnership_deed}}">Partnership deed</a>
                                  {% else %}
                                  Partnership deed not uploaded
                                  {% endif %}
                              </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Director partner list</td>
                                <td>
                                    {% for value in each.director_partner_list.all %}
                                       <a href=" {% url 'personal_data' %}{{ value }} ">{{ value }}</a>   
                                    {%endfor%}
                                </td>
                              </tr>
                              <tr>
                                
                              <tr>
                                <td>Remarks</td>
                                    <td>
                                        {{each.Remarks}}
                                    </td>
                              </tr>
                              <tr> <td style="text-align: center ">
                                <a href=" {% url 'company_data_edit' %}{{ each.code_no }}" class="btn btn-primary btnsubmit">Edit</a>
                              </td> </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                    <hr>
                {% endif %}
            </div>
        </div>
    </div>

    {% if a == False %}
    <div id="InfoBanner">
        <span class="reversed reversedRight">
          <span>
            &#9888;
          </span>
        </span>
        <span class="reversed reversedLeft">
          Warning {{errors}}!!
        </span>
    </div>
    {% endif %}



{% endblock %}

Personal_Data/templates/contact.html
{% extends "layout.html" %}
{% block title %}
Contact us
{% endblock %}
{% block heading %}
Contact us
{% endblock %}
{% block content %}
<p>Contact page for the Visual Studio Code Django tutorial.</p>
{% endblock %}

Personal_Data/templates/edit_employee_data.html
{% extends "layout.html" %}
{% block title %}
{{title}}{% endblock %}
{% block heading %}
{{title}}{% endblock %}
{% block content %}
<div class="container mt-5 text-center">
    <form action = "/update_Employee_details/{{id}}"  method = "post">
        <table class="table">
        <tbody>
            {% csrf_token %}
            {% for field in data %}
            <tr>
            <td>{{ field.label }}</td>
            <td>{{ field }}</td>
            </tr>
            <tr>
            {% endfor %}
            <tr>
            <td style="text-align: center ">
                <input type="submit" value="Submit">
            </td>
            </tr>
        </tbody>
        </table>
    </form>

    {{errors}}
</div>
{% endblock %}

Personal_Data/templates/forms_search_employee_data.html
{% extends "layout.html" %}
{% block title %}
{{title}}{% endblock %}
{% block heading %}
{{title}}{% endblock %}
{% block content %}


<div class="container" style="margin-top:5% ;">
    <div class="d-flex">
        <div class="row m-4">
            <h1>Search Employee by Code</h1>
            <div class="col-12 px-4 py-3">
                <div class="row mt-2">
                    <div class="col-lg-10">
                        <form method="post" style="margin-top: 5%" action="{% url 'search_Employee_details' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-2 col-12 mb-3">
                                    <label class="font-weight-bold" for="id_name">Emp_Code</label>
                                </div>
                                <div class="col-lg-6 col-12 mb-3">
                                    <input type="text" name="name" maxlength="30" required id="id_name">
                                </div>
                                <div class="col-4">
                                    <input type="submit" class="btn btn-primary btnsubmit" value="Submit">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                {% if a == True %}
                <div class="container mt-5 text-center">
                    <table class="table">
                        <tbody>
                            {% for each in data %}
                            <tr>
                                <td>{{each.Emp_Code}} </td>
                                <td>   
                                    <a class="btn btn-primary" href="/edit_Employee_details/{{ code }}">Edit</a>  
                                </td>  
                            </tr>
                            {%endfor%}
                      </tbody>
                    </table>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if a == False %}
        <div id="InfoBanner">
            <span class="reversed reversedRight">
            <span>
                &#9888;
            </span>
            </span>
            <span class="reversed reversedLeft">
            Warning {{errors}}!!
            </span>
        </div>
        {% endif %} 

    </div>
</div>   
{% endblock %}